resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: glue-viz
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - 'v*'

jobs:

- template: publish.yml@OpenAstronomy
  parameters:
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
      pypi_connection_name: 'pypi_endpoint'
    test_extras: test
    test_command: pytest --pyargs glue_jupyter
    targets:
    - sdist
    - wheels_universal

- template: run-tox-env.yml@OpenAstronomy
  parameters:

    coverage: codecov

    envs:

    - linux: codestyle
      libraries: {}
      coverage: false
      pytest: false

    - linux: py37-test
    - linux: py38-test
    - linux: py39-test

    - macos: py37-test
    - macos: py38-test
    - macos: py39-test

    - windows: py37-test
    - windows: py38-test
    - windows: py39-test

    - linux: py37-notebooks
      coverage: false
      pytest: false
    - macos: py38-notebooks
      coverage: false
      pytest: false
    - windows: py39-notebooks
      coverage: false
      pytest: false

    - linux: py39-docs
      coverage: false
      pytest: false
    - macos: py37-docs
      coverage: false
      pytest: false
    - windows: py38-docs
      coverage: false
      pytest: false
